In [4]:
my_list = [23,45,67,87]

In [2]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([23, 45, 67, 87])

In [7]:
list_of_list =[[3,5],[2,4],[44,66]]

In [8]:
list_of_list

[[3, 5], [2, 4], [44, 66]]

In [9]:
#2D array
_2d_arr = np.array(list_of_list)

In [10]:
_2d_arr

array([[ 3,  5],
       [ 2,  4],
       [44, 66]])

In [12]:
#arange generate an array
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
#required positional argument: 'shape' :1D
np.ones(5)

#np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
#2D
np.ones((2,5))
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
#linespace generate decimal point: np.linespace(start,stop,numberof)
np.linspace(2,3,4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [28]:
#identity 2d array
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
#random 1d array
np.random.random(5)

array([0.84481523, 0.16847628, 0.11473748, 0.59567542, 0.49415036])

In [30]:
#random 1d array
np.random.rand(5)

array([0.11434962, 0.45835201, 0.12401694, 0.26264888, 0.06438812])

In [32]:
#random 1d array
np.random.randint(5)
np.random.randint(1,10,5)

array([1, 6, 3, 9, 9])

In [50]:
#reshape the array
arr = np.arange(30) # np.arange(50).reshape(5,10)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [51]:
arr.reshape(5,6) # must a*b = total numbers of elements reshape (a,b)==(5,5)
reshaped_arr = arr.reshape(3,10)
reshaped_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [59]:
#access elements of 2d arr_name[r,c] = 
reshaped_arr[1,1] # 11
reshaped_arr[1][1] #11
reshaped_arr[2:,0] #20
reshaped_arr[1:2] # only deal with row if not have comma array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])
reshaped_arr[0:2,1:2]

array([[ 1],
       [11]])

In [42]:
#max, min
arr.max()
#index location
arr.argmax()

29

In [43]:
arr.min()
arr.argmin()

0

In [47]:
#shape()return error != shape
arr.shape

(30,)

In [49]:
#data type
arr.dtype

dtype('int32')

NumPy operations
Arrays with arrays
Arrays with scalars
universal array functions 

In [1]:
#use numpy to generate an array of 20 random numbers sampled from a standard normal distribution

import numpy as np
#generate an array of 20 random numbers sampled from a standard normal distribution
random_numbers = np.random.standard_normal(size=20)
print(random_numbers)


[-0.62739677  0.51551948  0.40709514 -0.10258019  2.12860322  0.04284907
  0.38128765  1.59874195  0.60544458 -0.55487051 -0.39434665 -0.83879733
  0.5232592   1.02121952 -0.99443735  0.55826834 -0.77701912 -0.07569514
 -0.79621788 -0.47216538]


In [4]:
#or 
np.random.randn(20)

array([ 0.94778849,  0.18833496,  0.62463287, -0.39252897, -0.11342326,
       -0.21327312, -0.75973088, -0.49049969, -0.87832461,  1.4936913 ,
       -1.58681022,  0.78347283, -0.96293391,  0.498724  , -0.21790183,
       -0.01683259,  0.9609523 ,  0.7712499 ,  1.4216299 , -0.90699918])

In [5]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [9]:
r=np.linspace(0.01,1,100).reshape(10,10) # the same with above 
r

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [10]:
r.sum()

50.5

In [11]:
np.std(r)

0.2886607004772212

In [24]:
#get the sum of columns of axis = 0 and axis=1 for column
sum_column = np.arange(1,7).reshape(2,3)
sum_column.sum(axis=0)


array([5, 7, 9])