In [4]:
my_list = [23,45,67,87]

In [2]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([23, 45, 67, 87])

In [7]:
list_of_list =[[3,5],[2,4],[44,66]]

In [8]:
list_of_list

[[3, 5], [2, 4], [44, 66]]

In [9]:
#2D array
_2d_arr = np.array(list_of_list)

In [10]:
_2d_arr

array([[ 3,  5],
       [ 2,  4],
       [44, 66]])

In [12]:
#arange generate an array
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
#required positional argument: 'shape' :1D
np.ones(5)

#np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
#2D
np.ones((2,5))
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
#linespace generate decimal point: np.linespace(start,stop,numberof)
np.linspace(2,3,4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [28]:
#identity 2d array
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
#random 1d array
np.random.random(5)

array([0.84481523, 0.16847628, 0.11473748, 0.59567542, 0.49415036])

In [30]:
#random 1d array
np.random.rand(5)

array([0.11434962, 0.45835201, 0.12401694, 0.26264888, 0.06438812])

In [32]:
#random 1d array
np.random.randint(5)
np.random.randint(1,10,5)

array([1, 6, 3, 9, 9])

In [50]:
#reshape the array
arr = np.arange(30) # np.arange(50).reshape(5,10)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [51]:
arr.reshape(5,6) # must a*b = total numbers of elements reshape (a,b)==(5,5)
reshaped_arr = arr.reshape(3,10)
reshaped_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [59]:
#access elements of 2d arr_name[r,c] = 
reshaped_arr[1,1] # 11
reshaped_arr[1][1] #11
reshaped_arr[2:,0] #20
reshaped_arr[1:2] # only deal with row if not have comma array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])
reshaped_arr[0:2,1:2]

array([[ 1],
       [11]])

In [42]:
#max, min
arr.max()
#index location
arr.argmax()

29

In [43]:
arr.min()
arr.argmin()

0

In [47]:
#shape()return error != shape
arr.shape

(30,)

In [49]:
#data type
arr.dtype

dtype('int32')